package error;

public enum ErrType {
    ADD_SLIDE_TO_PROJECT,
    ADD_PRESENTATION_TO_WORKSPACE,
    ADD_SLIDE_TO_WORKSPACE,
    ADD_PRESENTATION_TO_SLIDE,
    ADD_PROJECT_TO_SLIDE_,
    ADD_PROJECT_TO_PRESENTATION,

}
